name: pangle_flutter
description: A Flutter plugin that supports ByteDance Pangle SDK on Android and iOS. Such as Splash Ads, Rewarded Video Ads, etc.
version: 1.8.0
homepage: https://github.com/nullptrX/pangle_flutter

environment:
  sdk: '>=2.16.2 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  plugin:
    platforms:
      android:
        package: io.github.nullptrx.pangleflutter
        pluginClass: PangleFlutterPlugin
      ios:
        pluginClass: PangleFlutterPlugin

